# ---------------------------------------------------------
# feat: Add Kubernetes Services for backend, frontend & MongoDB
#
# - Ensures stable networking between microservices
# - Exposes backend & frontend to the cluster
# - Implements headless service for MongoDB discovery
# ---------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000  # Cluster-internal port
      targetPort: 5000  # Matches container's port
  type: ClusterIP  # Internal only—backend should not be exposed directly

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000  # Exposes frontend app
      targetPort: 3000
  type: LoadBalancer  # Allows external access to the frontend UI

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None  # Headless Service for MongoDB StatefulSet
