# ---------------------------------------------------------
# feat: Add Kubernetes backend deployment manifest
# 
# - Define backend deployment with one replica for efficiency
# - Set MongoDB connection string to reference Kubernetes service
# - Configure resource limits to stay within Free Tier constraints
# - Ensure proper container port exposure for backend services
# ---------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1  # We’re keeping it minimal for Free Tier
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kevindev1/yolo-backend:v1.0.6
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: mongodb-secret  # Inject MongoDB URI securely
          resources:
            limits:
              cpu: "100m"  # 
              memory: "128Mi"  # Keep memory usage within Free Tier
            requests:
              cpu: "100m"
              memory: "128Mi"
