
# Purpose: Ensure essential system packages are installed and updated. 
# Scope: Updates package lists, installs core utilities (Git, Curl, Docker), and prepares the environment for automation.

---
# tasks file for roles/system_config
- name: Update package list
  apt:
    update_cache: yes

- name: Install essential packages
  apt:
    name:
      - git
      - curl
      - docker.io
    state: present

- name: Enable Docker service
  systemd:
    name: docker
    state: started
    enabled: true
